# Generated by Django 4.0.2 on 2022-02-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
