# Generated by Django 4.0.2 on 2022-02-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_importer', '0003_myfile_products_created_products_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myfile',
            options={},
        ),
    ]
